name: libintl
description: Dart bindings for GNU GetText implementations.
version: 0.0.1
repository: https://github.com/gtk-dart/libintl

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.0.0
  args: ^2.4.2
  ffi: ^2.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
